---
title: "Predictive Modeling Semester Overview"
output: html_document
date: '2022-04-27'
---

##### Week 1  

###### 1. I learned the difference between overfitting and underfitting where an overfit model looks great on the training data but performs poorly on new data. However, underfitting occurs when both the training and generalization errors are large.  

###### 2. There are various solutions to overfitting such as expanding the training dataset and regularization which assists in determining the predictors that should be removed in order to simplify the model.  

##### Week 2 

###### 1. I gained knwoledge on dealing with imperfect data such as missing values. Some solutions were to drop the rows with missing values or convert or replace the missing values with meaningful values (imputation).  

###### 2. The difference between explanatory and exploratory analyses gave me a better understanding of data analysis. Exploratory analysis involves examining the data to find relationships and any specific features or characteristics while explanatory data analysis explains those findings that were determined in the exploratory stage to get a deeper insight.

##### Week 3  

###### 1. Linear regression is the first statistical method that should be used before using more complicated models. It builds a model in which the predicted numerical output in a linear additive function of the inputs.  

###### 2. One main assumption of linear regression are the non-correlation of residuals as correlation can result in estimated standard errors being underestimated.   

##### Week 4  

###### 1. When the response variable is qualitative, we should approach the classification process since linear regression assumes the response variable is quantitative. Therefore, logistic regression is the best first method as it predicts the probability that an isntance belongs to a specific category.   

###### 2. The perfomance evaluation measures for a classification model are confusion matrix, precision, recall, F1- score and the ROC curve. Precision is the ratio of true positives to the sum of true positives and false positives and recall is the ratio of true positives to the total of true positives and false negatives.  

##### Week 5  

###### 1. Learning another method to Linear regression known as GLM was also helpful. GLMs generalizes classical normal linear model by relaxing some of the restricitve assumptions. It can have non- normal errors or distribution and it does not need a constant variance as the simple linear regression.   

###### 2. GLM includes exponential family distributions such as Poission and Gamma distributions. The Poisson distribution is a discrete probability distribution whereas Gamma regression models a continuous response variable with a distribution that is non-negative and right-skewed.  

##### Week 6  

###### 1. The applications of decision trees to solve business porblems were also very insightful. Decision trees simplify the linear regression models as it can be displayed graphically and it can also handle categorical variables or predictors.  

###### 2. Gradient Boosting Machines(GBMs) create a stronger model by combining weak predictors, usually decision trees. They provide more accurate predicitons although they are more susceptible to overfitting and can handle both numerical and categorical variables.  

##### Week 7   

###### 1. Clustering is an example of exploratory data analysis and also an application of unsupervised learning. It is the process of grouping data based on distinct similarities or differences. K-means clustering is one popular approach although there are others such as hierarchal clustering and probabilistic clustering.  

###### 2. Another main application of unsupervised learning is dimensionality reduction which reduces the number of variables in a dataset to a more manageable size in order to simplify the dataset before further analysis.  

##### Week 8 

###### 1. I learned the importance of GitHub and its uses in the data science field such as tracking changes to codes and sharing it with others. The numerous Git commands (ex. git clone, git push, git commit, git log, git status etc) all have very important and useful functions.  

###### 2. The importance of proper preparation and presentation skills were also emphasized. I was able to learn about creating ioslides presentations from RMarkdown and the various ways to customize slides to create an effective and appealing presentation.  